name: Container Image CI

on: [push]

defaults:
  run:
    working-directory: ./

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    name: Build native Quarkus app
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
      - name: Build quarkus
        run: ./mvnw package -B -Pnative
      - name: Build container image
        uses: docker/build-push-action@v3
        with:
          file: src/main/docker/Dockerfile.native-micro
          context: ./
          push: true
          network: host
          tags: |
            ghcr.io/cloudschamanen/mpe:${{ github.sha }}
          labels: |
            org.opencontainers.image.source=https://github.com/cloudschamanen/mpe

