on: [push]

jobs:
  native_build:
    runs-on: ubuntu-latest
    name: Build native Quarkus app
    steps:
      - name: Checkout the code
        uses: actions/checkout@master
      
      - name: Build native executable and upload it as an artifact
        uses: maxday/quarkus-native-build-docker-action@master
        with:
          outputName: mpe
      
      - name: Upload native executable
        uses: actions/upload-artifact@v1
        with:
          name: native-executable
          path: mpe
      
      - name: Dockerize
        uses: maxday/quarkus-dockerize-action@master
        with:
          tag: ghcr.io/cloudschamanen/mpe
          executablePath: native-executable/mpe

